fix login and signup with google
atlp-rwanda/elite-bn-backend pull request #34
Opened 2021-03-06 07:56 UTC by iradukundairenee

fix social auth issue

2021-03-08 06:56 UTC, cniyindagiriye requested changes

2021-03-08 06:56 UTC, cniyindagiriye commented on src/controllers/socialAuth.js
> +      Location: `http://localhost:8080/dashboard?name=${fullName}&email=${email}&roleId=${roleId}&token=${token}`
Use url we've hosted front-end app when you push.
[elite-bn-frontend](https://barefoot-nomads.netlify.app/)

2021-03-09 16:14 UTC, cniyindagiriye approved these changes

2021-03-09 17:53 UTC, ShemaM approved these changes

2021-03-09 20:06 UTC, merged