Ft travelrequest docs
atlp-rwanda/elite-bn-backend pull request #44
Opened 2021-03-19 14:17 UTC by iradukundairenee

adding documentation to travel requesrt

2021-03-21 06:50 UTC, NIRoberto approved these changes

2021-03-22 07:47 UTC, Patricknshimiyimana approved these changes

2021-03-22 08:39 UTC, cniyindagiriye requested changes

2021-03-22 08:39 UTC, cniyindagiriye commented on src/docs/travelRequest.js
> +*        - multipart/form-data
You may use `- application/json`
this link can help you how to de describe Request Body: [swagger docs](https://swagger.io/docs/specification/2-0/describing-request-body/)

2021-03-22 08:39 UTC, cniyindagiriye commented on src/docs/travelRequest.js
> +*       - in: formData
you may pass parameters as body instead of formData

2021-03-22 08:39 UTC, cniyindagiriye commented on src/docs/travelRequest.js
> +/**
![Screenshot from 2021-03-22 09-48-11](https://user-images.githubusercontent.com/50295185/111961772-1ee95f80-8afa-11eb-9974-ebda6e02f67e.png)

2021-03-23 07:37 UTC, mukunzidd requested changes
- @iradukundairenee why did you delete `.env.example`?
- Please write a good description for the PR

2021-03-23 11:05 UTC, cniyindagiriye approved these changes

2021-03-29 07:12 UTC, mukunzidd approved these changes

2021-03-30 07:44 UTC, merged